import { authOptions } from '@/pages/api/auth/[...nextauth]'
import 'bootstrap/dist/css/bootstrap.min.css'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Board',
  description: 'Generated by Benedict'
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  let session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
